title: BiFlow Catalogue
baseurl: "/biflow_website" # the subpath of your site, e.g. /blog
url: "https://tmancinelli.github.io/biflow_website"
description: something..
email: foo@bar.it

# Build settings
markdown: kramdown
