version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  jekyllbuild:
    build:
      context: .
      args:
        build_command: "jekyll build"
    volumes:
      - ".:/srv/jekyll"
  nginx:
    image: nginx
    volumes:
      - "./_site:/var/www/public"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./_site/404.html:/usr/share/nginx/html/404.html"
    ports:
      - 80:80
 
